name: areej
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0 

dependencies:
  flutter:
    sdk: flutter
  uuid: ^3.0.6
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  firebase_core: ^3.9.0  
  firebase_auth: ^5.3.4 
  flutter_riverpod: ^2.6.1
  google_sign_in: ^6.2.2
  flutter_rating_bar: ^4.0.1
  flutter_easyloading: ^3.0.5
  flutter_timezone: ^4.0.0
  cloud_firestore: ^5.6.0
  image_picker: ^1.1.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  location: ^7.0.1
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets section
  assets:
    - assets/img/
    - assets/font/

  # Fonts section
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/font/Metropolis-Medium.otf
        - asset: assets/font/Metropolis-Regular.otf
          weight: 500
        - asset: assets/font/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/font/Metropolis-Bold.otf
          weight: 700
        - asset: assets/font/Metropolis-ExtraBold.otf
          weight: 800

# flutter_native_splash:
#   color: "#FFFFFF" # Replace with your app's primary background color
#   image: assets/img/splash_bg.png # Path to your splash screen logo
#   android: true # Enable splash screen for Android
#   ios: true # Enable splash screen for iOS
#   web: false # Disable splash screen for web
#   android_gravity: center # Center the image on Android
#   ios_content_mode: center # Center the image on iOS
#   fullscreen: true # Use fullscreen splash screen
#   android_background: "assets/img/splash_bg.png" # Background image for Android
#   android_logo: "assets/img/app_logo.png" # Logo for Android
#   logo_width: 150 # Width of the logo
#   logo_height: 150 # Height of the logo
#   logo_alignment: center # Center the logo